### ISSUE TITLE
Peephole

### ISSUE THREAD

**Issue by 0x454447415244** [hannw/nlstm#1]
Hello, thanks for this code.
Is it possible to add peephole connections as in the rnn cell of tensorflow?
Thanks

**Comment by hannw** [comment]
Peephole added in #2. Thanks for the suggestion.

**Comment by 0x454447415244** [comment]
Thanks. I also thought of adding an option for weight initialization.

**Comment by hannw** [comment]
sure, feel free to submit a PR.
